config/routes.rb
SupportTracker::Application.routes.draw do
  resources :tickets do
    collection { get :track }
  end

  devise_for :users

  root 'tickets#index'

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  extend FriendlyId
  friendly_id :uniq_reference, use: :slugged

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_UNIQ_REFERENCE = /\w{3}-\d{3}-\w{3}-\d{3}-\w{3}/

  validates :customer_name,  presence: true, length: { maximum: 50 }
  validates :subject,  presence: true, length: { maximum: 50 }
  validates :ticket_body,  presence: true, length: { maximum: 1000 }
  validates :customer_email, presence: true, format: { with: VALID_EMAIL_REGEX }

  max_paginates_per 10

  # after_initialize :make_uniq_reference

  def self.all_statuses
    ['Waiting for Staff Response', 'Waiting for Customer', 'On Hold',
     'Cancelled', 'Completed']
  end

  def self.all_interfaces
    ['New unassigned tickets', 'Open Tickets', 'On hold tickets',
     'Closed Tickets']
  end

  def make_uniq_reference
    begin
      self.uniq_reference = VALID_UNIQ_REFERENCE.gen.upcase
    end while Ticket.where(uniq_reference: self.uniq_reference).exists?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         # :validatable,
         :authentication_keys => [:username]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
      devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
      devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
      # debugger
    if ! params[:search].blank?
      @ticket = Ticket.find_by slug: params[:search].downcase
      redirect_to ticket_path(@ticket) unless @ticket.nil?
    end
    @tickets = Ticket.all

  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
    @whois = :customer
  end

  # GET /tickets/1/edit
  def edit
    if @ticket.ticket_status.in? ['Cancelled', 'Completed']
      redirect_to ticket_path(@ticket), alert: "This ticket is
      #{@ticket.ticket_status}."
    else
      if user_signed_in?
        @whois = :staff
      else
        @whois = :customer
      end
    end
  end
  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.ticket_status = 'Waiting for Staff Response'
    @ticket.ticket_interface = 'New unassigned tickets'
    @ticket.make_uniq_reference

    TicketConfirmingMailer.new_ticket_confirmation(@ticket).deliver

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ticket }
      else
        format.html { render action: 'new' }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  def track
    # debugger
    if user_signed_in?
      # @tickets = Ticket.all.page(params[:page])
      @tickets = Ticket.order(:id).page(params[:page]).per(5)
    else
      redirect_to new_user_session_path, alert: 'Please Sign in.'
    end
  end

  def update
    if user_signed_in?
      @ticket.ticket_status = params[:ticket][:ticket_status] || 'Waiting for Customer'
      @ticket.ticket_interface = (@ticket.ticket_status.in? ['Cancelled', 'Completed']) ? 'Closed Tickets' : 'Open Tickets'
      # debugger
      @ticket.ownership = params[:ticket][:ownership] || current_user.username
      TicketConfirmingMailer.new_ticket_confirmation(@ticket).deliver
    else
      @ticket.ticket_status = 'On Hold'
      @ticket.ticket_interface = 'On hold tickets'
    end
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render action: 'show', status: :ok, location: @ticket }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:customer_name, :customer_email, :subject, :uniq_reference, :ticket_status, :ticket_interface, :ownership, :ticket_body, :response)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{class: "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", type: "button"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      -# = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav= render 'layouts/navigation_links'
      %form.navbar-form.navbar-left{role: "search"}
        .form-group
          %input.form-control{placeholder: "Search", type: "text"}/
        %button.btn.btn-default{type: "submit"} Submit
      / %ul.nav.navbar-nav.navbar-right
      /   %li
      /     %a{href: "#"} Link
      /   - if user_signed_in?
      /     Logged in as
      /     = succeed "." do
      /       %strong= current_user.username
      /     = link_to 'Edit profile', edit_user_registration_path
      /     |
      /     \#{link_to "Logout", destroy_user_session_path, method: :delete}
      /   - else
      /     = link_to "Sign up", new_user_registration_path
      /     |
      /     \#{link_to "Login", new_user_session_path}

app/views/layouts/_navigation_links.html.haml
-# add navigation links to this file
-# in app/views/movies/show.html.haml
%li= link_to 'Home', root_path
%li= link_to 'New Ticket', new_ticket_path
%li= link_to 'Track Ticket', track_tickets_path

%p.navbar-text.navbar-right
  - if user_signed_in?
    Logged in as
    = succeed "." do
      -# %strong= current_user.email
      %strong= current_user.username
    = link_to 'Edit profile', edit_user_registration_path, class: 'navbar-link'
    |
    \#{link_to "Logout", destroy_user_session_path, method: :delete, class: 'navbar-link'}
  - else
    = link_to "Sign up", new_user_registration_path, class: 'navbar-link'
    |
    \#{link_to "Login", new_user_session_path, class: 'navbar-link'}

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Support Tracker"
    %meta{content: content_for?(:description) ? yield(:description) : "Support Tracker", name: "description"}/
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %header= render 'layouts/navigation'
    %main{role: "main"}
      = render 'layouts/messages'
      = yield

app/views/tickets/_form.html.haml
= form_for(@ticket, :html => { class: 'form-horizontal', role: 'form' }) do |f|
  .form-group
    - if @ticket.errors.any?
      #error_explanation
        %h2
          = pluralize(@ticket.errors.count, "error")
          prohibited this ticket from being saved:
        %ul
          - @ticket.errors.full_messages.each do |msg|
            %li= msg
  -# - if @whois == :customer
  -# debugger
  .form-group.col-lg-4
    = f.label :customer_name
    = f.text_field :customer_name, (@ticket.uniq_reference.nil?) ? {cols: '20', class: 'form-control'} : {disabled:'disabled', class: 'form-control'}
    %br/
    = f.label :customer_email
    = f.text_field :customer_email, (@ticket.uniq_reference.nil?) ? {cols: '20', class: 'form-control'} : {disabled:'disabled', cols: '20', class: 'form-control'}
    %br/
    = f.label :subject
    = f.text_field :subject, (@whois == :staff) ? {disabled:'disabled',  cols: '20', class: 'form-control'} : { cols: '20', class: 'form-control'}
    - if @whois == :staff
      %br/
      = f.label :uniq_reference
      = f.text_field :uniq_reference, disabled: 'disabled',  cols: '20', class: 'form-control'
      %br/
      = f.label :ticket_status
      -#= f.text_field :ticket_status, cols: '30'
      -#= select_tag(:ticket_status, options_for_select([['Waiting for Customer'], ['On Hold'], ['Cancelled'], ['Completed']]), class: 'form-control')
      = f.select(:ticket_status, options_for_select([['Waiting for Customer'], ['On Hold'], ['Cancelled'], ['Completed']]), class: 'form-control')
      %br/
      = f.label :ticket_interface
      = f.text_field :ticket_interface, cols: '30', disabled:'disabled', class: 'form-control'
      %br/
      = f.label :ownership
      -#= f.text_field :ownership, (@ticket.ownership) ? {disabled:'disabled'} : {disabled: 'disabled', hidden: 'true'}
      = f.text_field :ownership, class: 'form-control'
    %br/
    = f.label :ticket_body
    = f.text_area :ticket_body, (@whois == :staff) ? {disabled:'disabled', rows: '5',cols: '30', class: 'form-control'} : {rows: '10', class: 'form-control'}
    - if @whois == :staff
      %br/
      = f.label :response
      = f.text_area :response, class: 'form-control'
    %br/
    = f.submit 'Update Ticket', class: 'btn btn-default'

app/views/tickets/edit.html.haml
.well.well-small
  .page-header
    .col-lg-1
    %h1
      Support Issue Tracker
      %small Edit Ticket Page
.container
  .col-lg-1
  = render 'form'
  %br/
.container
  .col-lg-2
    = link_to 'Show', @ticket
    |
    \#{link_to 'Back', tickets_path}

app/views/tickets/index.html.haml
.well.well-small
  .page-header
    .col-lg-1
    %h1
      Support Issue Tracker
      %small Welcome Page
.container
  .col-lg-4
    = form_tag tickets_path, method: 'get', class: 'form-inline', :role => 'form', multipart: true do
      .form-group
        = text_field_tag :search, nil, {class: 'form-control', :style => 'width: 15em;', placeholder: "ABC-123-ABC-123-ABC", type: "text"}
      = button_tag(type: 'submit', class: 'btn btn-default') do
        %span.glyphicon.glyphicon-search
  .col-lg-8
    / Body content
    Welcome to the home page of the Support Office, which is situated within  Services Centre.

app/views/tickets/new.html.haml
.well.well-small
  .page-header
    .col-lg-1
    %h1
      Support Issue Tracker
      %small New Ticket Page
.container
  .col-lg-1
  .col-lg-11
    = render 'form'

%br/
.container
  .col-lg-2
    = link_to 'Back', tickets_path

app/views/tickets/show.html.haml
.well.well-small
  .page-header
    .col-lg-1
    %h1
      Support Issue Tracker
      %small Show Page
.container
  .col-lg-12
    / Body content
    %p#notice= notice
    %p
      %strong Customer name:
      = @ticket.customer_name
    %p
      %strong Customer email:
      = @ticket.customer_email
    %p
      %strong Subject:
      = @ticket.subject
    %p
      %strong Uniq reference:
      = @ticket.uniq_reference
    %p
      %strong Ticket status:
      = @ticket.ticket_status
    %p
      %strong Ticket interface:
      = @ticket.ticket_interface
    %p
      %strong Ownership:
      = @ticket.ownership
    %p
      %strong Ticket body:
      = @ticket.ticket_body
    %p
      %strong Response:
      = @ticket.response
    = link_to 'Edit', edit_ticket_path(@ticket)
    |
    \#{link_to 'Back', tickets_path}

app/views/tickets/track.html.haml
.well.well-small
  .page-header
    .col-lg-1
    %h1
      Support Issue Tracker
      %small Staff Page
.container
  .col-lg-2
  .col-lg-10
  / Body content
  %table.table.table-hover
    /- debugger
    %thead
      %tr
        %th
        %th Name
        %th Email
        %th Subject
        %th Status
        %th Interface
    %tbody
      - @tickets.each_with_index do |ticket, i|
        %tr{class: cycle('active', 'success', 'info'), onclick: "document.location = '#{edit_ticket_path(ticket)}'"}
          %td= i+1
          %td= ticket.customer_name
          %td= ticket.customer_email
          %td= %Q{#{truncate("#{ticket.subject}", length: 20)}}
          %td= ticket.ticket_status
          %td= ticket.ticket_interface
    %tfoot.text-right
    %tr
      %td
      %td
      %td
      %td
      %td
      %td= paginate @tickets, theme: 'twitter-bootstrap-3'

  = link_to 'Back', tickets_path